### ISSUE TITLE
负数金额

### ISSUE THREAD

**Issue by 63815af756f0357940c666d2ae1c801d** [zhang-anzhi/Economy#1]
钱不够了似乎也能pay...

**Comment by zhang-anzhi** [comment]
插件还未写完，感谢提醒，pay和take功能会加判断保障非负余额

**Comment by 63815af756f0357940c666d2ae1c801d** [comment]
个人意见，take作为op的功能，其实可以把人的钱扣到负的
在pay上做判断就行了

**Comment by zhang-anzhi** [comment]
当前take功能已经完成，扣多了就调整为0
可以看一下readme和源码，pay功能更新后会做判断的

**Comment by zhang-anzhi** [comment]
已经完成了除了top以外的功能，该问题已解决
