### ISSUE TITLE
向空账号能够成功转账，并且扣钱。

### ISSUE THREAD

**Issue by XiaoHuiHui233** [zhang-anzhi/Economy#4]
![image](https://user-images.githubusercontent.com/21187839/81514521-309e9a00-9362-11ea-97de-c527899c3d2d.png)
这个bug有点致命 你不能保证有些玩家不会把转账人的名字打错，并且收款人并不能看到转账信息进行核实 另外就是转走的钱凭空消失了
（你的插件允许向未在线的玩家转账，我觉得这应该算一个特性）

**Comment by zhang-anzhi** [comment]
可以向空账号转账是修改函数return不全导致的，可以操作未在线玩家账户属于正常特性

**Comment by zhang-anzhi** [comment]
已修复，试一下
